[package]
name = "cosignerd"
version = "0.0.1"
authors = ["JSwambo <jake.t.swambo@hotmail.co.uk>", "Antoine Poinsot <darosior@protonmail.com>"]
edition = "2018"

[dependencies]
dirs = "3.0"
daemonize-simple = "0.1"

# TOML for the config
toml = "0.5"

# For the messages
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"

# Logging
log = "0.4"
fern = "0.5"
chrono = "0.4"

rusqlite = { version = "0.24.2", features = ["bundled"] }

# Revault
revault_net = { git = "https://github.com/revault/revault_net" }
revault_tx = { version = "0.1", features = ["use-serde"] }

# For fuzz testing
libc = { version = "0.2", optional = true }
bitcoin = {version = "0.25.2", features = ["rand"], optional = true}

[features]
fuzztesting = ["libc", "bitcoin"]

[dev-dependencies]
libc = "0.2"
bitcoin = {version = "0.25.2", features = ["rand"]}
